name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild.exe path
        run: |
          sudo apt-get install -y apt-transport-https
          sudo apt-get update
          sudo apt-get install -y mono-devel
          sudo apt-get install -y msbuild
          echo "msbuild: $(which msbuild)"
        
      - name: Build
        run: |
          msbuild /p:Configuration=Release /p:TargetFrameworkVersion=v3.5
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: COM3D2.ShapeAnimator.Plugin
          path: COM3D2.ShapeAnimator.Plugin/bin/Release/COM3D2.ShapeAnimator.Plugin.dll
